apiVersion: v2
name: service-card
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: '1.16.0'
dependencies:
  - name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 18.x.x
  # - name: postgresql
  #   repository: oci://registry-1.docker.io/bitnamicharts
  #   version: 10.x.x
  # - name: minio
  #   repository: oci://registry-1.docker.io/bitnamicharts
  #   version: 8.x.x