apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
  labels:
    app: {{.Chart.Name}}
    heritage: {{.Release.Service}}
    release: {{.Release.Name}}
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    tire: microservice
    service: click-app

spec:
  replicas: {{default 1 .Values.replicas}}
  selector:
    matchLabels:
      app: {{.Chart.Name}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{.Chart.Name}}
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - name: {{.Chart.Name}}
          image: '{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}'
          imagePullPolicy: 'Always'
          ports:
            - containerPort: {{.Values.deploymentConfig.containerPort}}
          envFrom:
            - configMapRef:
                name: {{.Chart.Name}}
            - secretRef:
                name: {{.Chart.Name}}
