apiVersion: v1
kind: Secret
metadata:
  name: {{.Chart.Name}}
  namespace: {{.Release.Namespace}}
  labels:
    app: {{.Chart.Name}}
    heritage: {{.Release.Service}}
    release: {{.Release.Name}}
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
type: opaque
stringData:
  SERVICE_API_JWT_SECRET: {{ .Values.secretMap.SERVICE_API_JWT_SECRET | quote }}
  SERVICE_API_POSTGRES_PASSWORD: {{ .Values.secretMap.SERVICE_API_POSTGRES_PASSWORD | quote }}
  MINIO_ACCESS_KEY: {{ .Values.secretMap.MINIO_ACCESS_KEY | quote }}
  MINIO_SECRET_KEY: {{ .Values.secretMap.MINIO_SECRET_KEY | quote }}
